mode: TEST
listenaddr: localhost
listenport: 8080
pubdir: static
db:
    sqldriver: MySQL
    protocol: tcp
    hostname: localhost
    username: root
    password: 123456
    dbname: test
    charset: utf8